apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    release: kube-prometheus-stack
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 45.6.0
    helm:
      skipCrds: true
      values: |-
        prometheus:
          prometheusSpec:
            serviceMonitorSelector:
              matchLabels:
                prometheus: argo-cd-grafana
            additionalScrapeConfigs: |
              - job_name: 'argocd'
                scrape_interval: 30s
                scrape_timeout: 10s
                static_configs:
                  - targets: ['argocd-application-controller-metrics.argocd.svc.cluster.local:8082', 'argocd-redis-metrics.argocd.svc.cluster.local:9121']
              - job_name: 'alertManager'
                scrape_interval: 30s
                scrape_timeout: 10s
                static_configs:
                  - targets: ['alertmanager-operated.argocd.svc.cluster.local:9093']
        alertmanager:
          enabled: true
          config:
            route:
              routes:
              - receiver: 'flock'
                matchers:
                  - alertname =~ "(.*)"
            receivers:
            - name: 'flock'
              webhook_configs:
              - url: 'https://api.flock.com/hooks/sendMessage/f9775a46-b612-4c17-9808-1a83f6dd0142'
        nodeExporter:
          enabled: false
    chart: kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
